#on:
#  schedule:
#  - cron: "*/5 * * * *"

# For testing, use the star action in GitHub to trigger the action.
# TODO: Remove this after testing.
on:
  watch:
    types: [started]

jobs:
  run-buildapp:
    runs-on: ubuntu-latest
    name: Run App Builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run buildapp
        uses: ./.github/actions/run-buildapp
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_APP_ID: ${{ secrets.NETLIFY_APP_ID }}
        with:
          buildapp-command: '${GITHUB_WORKSPACE}/src/buildapp.sh'
